### ISSUE TITLE
[bug] Fails to login firebase-admin after updating to 5.13.0

### ISSUE THREAD

**Issue by joseph1125** [firebase/firebase-admin-node#308]
* Operating System version: Windows 8.1
  * Firebase SDK version: 5.13.0
  * Library version: Unknown
  * Firebase Product: firebase-admin-node

#### Steps to reproduce:

After updating firebase-admin-node from 5.12.1 to 5.13.0, the library fails to recognize the service account that I put in (I checked and it is valid) and go back to check the default credentials. 

UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

Rolling back to 5.12.1 solves the issue.

#### Relevant Code:

```
import * as admin from 'firebase-admin';
const serviceAccount = require('../../service-account-key.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://lice-line-bot.firebaseio.com'
});
const db = admin.firestore();
db.settings({timestampsInSnapshots: true});
```

**Comment by hiranya911** [comment]
Did some more digging, and it looks like the above 2 issues are actually independent. But I was able to repro @joseph1125's issue as well. New version of Firestore (0.15.x) does indeed try to look up ADC even when a service account is explicitly specified. Can be easily reproduced by setting `GOOGLE_APPLICATION_CREDENTIALS` to a bogus path like `/foo/bar`:

```
(node:73261) UnhandledPromiseRejectionWarning: Error: The file at /foo/bar does not exist, or it is not a file. Error: ENOENT: no such file or directory, lstat '/foo'
    at GoogleAuth.createError (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:516:16)
    at GoogleAuth.<anonymous> (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:366:32)
    at step (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at /Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:18:12)
    at GoogleAuth._getApplicationCredentialsFromFilePath (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:348:16)
    at GoogleAuth.<anonymous> (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:291:48)
    at step (/Users/hkj/Projects/firebase-admin-node/temp/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
```

Issue goes away, if Firestore 0.15.x is deleted from node_modules and 0.14.x is installed instead.

**Comment by hiranya911** [comment]
Fixed in the Firestore 0.15.4 release. Please re-install `firebase-admin` to get the latest dependencies.

**Comment by ggaabe** [comment]
Getting the same issue. A warning about the timestamps, and then a permission denied error.

**Comment by schmidt-sebastian** [comment]
@ggabe If you still see this issue after upgrading to v0.15.4, please let us know.

**Comment by schmidt-sebastian** [comment]
Can you share your output from

```
 npm list | grep '@google-cloud/firestore'
  ├─┬ @google-cloud/firestore@0.15.4
```

Thanks!

If you still see an older version, you need to remove and re-install `firebase-admin` along with its `@google-cloud/firestore` dependency, since NPM will otherwise use the already installed version. I would recommend that you remove your `node_modules` folder. If you still see `0.15.3` afterwards, you might also want to remove you package-lock.json or manually force an install of 0.15.4 using `npm install @google-cloud/firestore@0.15.4`.

**Comment by ggaabe** [comment]
Seems my firestore version is correct. Here's my output:

> │ ├─┬ @google-cloud/firestore@0.15.4
> npm ERR! peer dep missing: firebase-admin@~5.12.1, required by firebase-functions@1.1.0

**Comment by ggaabe** [comment]
I get an error:

TypeError: admin.firestore.setLogFunction is not a function


On Wed, Jul 18, 2018 at 4:23 PM, Sebastian Schmidt <notifications@github.com

**Comment by schmidt-sebastian** [comment]
> I get an error:
> 
> TypeError: admin.firestore.setLogFunction is not a function

Hm, that seems strange. That functionality hasn't been touched in a while. I wonder if there is something going on with your setup.

**Comment by hiranya911** [comment]
@ggaabe I think your set up is in a broken state at this point. I was able to enable logging and test the above scenario without any issues. Try removing the `node_modules/` directory along with any lock files, and reinstalling the dependencies. Also if you're using `firebase-functions` I'd recommend you to not upgrade to Admin 5.13.0 at this point. `firebase-functions` currently has a peer dependency on Admin 5.12.1, and it hasn't been tested with latest.

**Comment by ggaabe** [comment]
Writing to firestore now is working without any issue. I haven't changed the code, so something must be working right on your end now.
