### ISSUE TITLE
typescript definitions conflict with v6.0.0 & @google-cloud/storage and @google-cloud/firestore

### ISSUE THREAD

**Issue by ovaris** [firebase/firebase-admin-node#358]
Hi,

I have a project which uses firebase-admin & @google-cloud/storage and @google-cloud/firestore.
After upgrading to firebase-admin v6.0.0 I get following typescript errors:

```
node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/@google-cloud/firestore/types/firestore.d.ts:79:5 - error TS2374: Duplicate string index signature.

79     [key: string]: any; // Accept other properties, such as GRPC settings.
       ~~~~~~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/index.d.ts:18:9 - error TS2305: Module '"/Users/ovaris/programming/fs-server/node_modules/@google-cloud/storage/build/src/index"' has no exported member 'Bucket'.

18 import {Bucket} from '@google-cloud/storage';
           ~~~~~~

node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file
```

**Comment by ovaris** [comment]
Actually it seems that culprit seems to be latest `0.17.0` version of `@google-cloud/firestore`.
Also `2.0.3` version of `@google-cloud/storage` has broke typings:
```
node_modules/firebase-admin/lib/index.d.ts:18:9 - error TS2305: Module '"/Users/ovaris/programming/fs-server/node_modules/@google-cloud/storage/build/src/index"' has no exported member 'Bucket'.

18 import {Bucket} from '@google-cloud/storage';
```

**Comment by orcuns** [comment]
```

node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/@google-cloud/firestore/types/firestore.d.ts:79:5 - error TS2374: Duplicate string index signature.

79     [key: string]: any; // Accept other properties, such as GRPC settings.
       ~~~~~~~~~~~~~~~~~~~

node_modules/firebase-admin/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.
```

I'm getting the same error

**Comment by vdiaz1130** [comment]
Had the same issue. This fixed it for me:

npm i @google-cloud/storage@latest --save

**Comment by LukeStonehm** [comment]
We too are experiencing this issue, we have temporarily cast the object to 'any'.

Using latest `@google-cloud/storage` does not resolve it for us.

**Comment by ckmluna2** [comment]
@vdiaz1130 This did not seem to help. I'm still getting the same error.

**Comment by minstn** [comment]
Same problem here:

package versions
+ @google-cloud/storage@2.0.3
+ @google-cloud/firestore@0.17.0

node version:
v8.12.0

`node_modules/firebase-admin/lib/index.d.ts(18,9): error TS2305: Module '"/Users/mstonys/one/one/functions/node_modules/@google-cloud/storage/build/src/index"' has no exported member 'Bucket'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/one/.npm/_logs/2018-09-26T06_11_51_398Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code2`

**Comment by juliamazur** [comment]
I have the same problem with the newest packages.

**Comment by Meg4mi** [comment]
I have the same issue here :)

**Comment by rubio05** [comment]
Having the same issue

**Comment by theoafactor** [comment]
I have the same issue. Backward versions don't seem to help

**Comment by lupas** [comment]
Same issue here. I'm currently sticking with @google-cloud/storage v1.7.0 since an upgrade to v2 breaks with the error that @ovaris is mentioning.

**Comment by gtcdevop** [comment]
Same man, have a nice cup of coffee, and if I can help, I will !

**Comment by Jbz797** [comment]
Some news about this issue ?

**Comment by mlejva** [comment]
Also having same issue. Shouldn't this be given higher priority since it's basically breaking Typescript's build?

**Comment by mlejva** [comment]
I opened new issue at google-cloud/storage repo - [here](https://github.com/googleapis/nodejs-storage/issues/433)

**Comment by otnielgomez** [comment]
As a work arround in your /node_modules/firebase-admin/lib/index.d.ts replace:

**Line 18**
Instead of:
import {Bucket} from '@google-cloud/storage';

Use: 
import {Storage} from '@google-cloud/storage';

**AND Line 589**

Instead of:
bucket(name?: string): Bucket;

Use: 
bucket(name?: string): Storage;


It worked for me, im using: 

"@google-cloud/storage": "^2.0.3",
"firebase-admin": "~5.12.1",
"firebase-functions": "^2.0.5"

**Comment by lupas** [comment]
seems to work again with the recently released "@google-cloud/storage": "^2.1.0", guess this can be closed.

**Comment by mlejva** [comment]
> seems to work again with the recently released "@google-cloud/storage": "^2.1.0", guess this can be closed.

How are you importing `Storage`?

With 
```
import { Storage } from '@google-cloud/storage';
```
I'm getting following error
```
Module '"node_modules/@types/google-cloud__storage/index"' has no exported member 'Storage'.
```

**Comment by lupas** [comment]
>
> How are you importing `Storage`?
> 
> With
> 
> ```
> import { Storage } from '@google-cloud/storage';
> ```
> I'm getting following error
> 
> ```
> Module '"node_modules/@types/google-cloud__storage/index"' has no exported member 'Storage'.
> ```

Using typescript, I'm doing:
```
import * as admin from 'firebase-admin'
const storage = admin.storage()
```

Which threw the error mentioned above before, but since v2.1.0 it works again for me.

**Comment by ovaris** [comment]
@lupas Issue still remains, you cannot use `firebase-admin` package together with latest `@google-cloud/storage` because of TS identifier conflicts . You are using storage from inside `firebase-admin` which I would not like to do.

**Comment by ovaris** [comment]
Created a PR https://github.com/firebase/firebase-admin-node/pull/368

**Comment by kmturley** [comment]
Isn't this because firebase admin uses **@types/google-cloud__storage**:

 ```
"firebase-admin": {
      "version": "6.0.0",
      "requires": {
        "@firebase/app": "0.3.4",
        "@firebase/database": "0.3.6",
        "@google-cloud/firestore": "0.16.1",
        "@google-cloud/storage": "1.7.0",
        "@types/google-cloud__storage": "1.7.2",
        "@types/node": "8.10.36",
        "jsonwebtoken": "8.1.0",
        "node-forge": "0.7.4"
      }...
```

But the package already has it's own definitions?
https://www.npmjs.com/package/@google-cloud/storage
https://github.com/googleapis/nodejs-storage/blob/master/src/index.ts

If I do:
`rm -rf node_modules/@types/google-cloud__storage`

then it bypasses the error

**Comment by rodleviton** [comment]
I know it is not pretty but here is a temporary" workaround to get your code to compile and ignore the conflict. Inside your `tsconfig.json` add the following:

```
{
    "compilerOptions": {
        "skipLibCheck": true,
        ...
    },
}
```

Read more about this option here: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/release%20notes/TypeScript%202.0.md#new---skiplibcheck

**Comment by hiranya911** [comment]
This upgrade has been scheduled for the next major release. We are working internally to figure out the timeline.

**Comment by Wang-Po-Chang** [comment]
Hi 
In my project, i also have the same issue.
and i solve it, like this.
I hope this can help you
![image](https://user-images.githubusercontent.com/46281116/50561035-bd365280-0d41-11e9-8eb1-0dfb73890a30.png)


I have not use @google-cloud/firestore

**Comment by dinvlad** [comment]
Having the same issue with `@google-cloud/firestore` v0.20.0 upwards (v0.19.0 works fine). Is there any update on when it's resolved?

(OT here, but we have to resort to using `@google-cloud/firestore` only because of the `timestampsInSnapshots` warning)

**Comment by hiranya911** [comment]
This has been fixed in the master branch, and included in the next major release. See #437 and #451 for progress.

**Comment by Mikkelet** [comment]
Im having this problem now. What's weirder is, I am using the EXACT same dependencies for the project thats tied to a test firestore database and IT has no problem deploying the functions. So weird.

**Comment by whaatt** [comment]
@Mikkelet Try using exact versions instead of approximate (`~` or `^`) versions, especially if you haven't upgraded to `@google-cloud/firestore@3`.

The`firebase-admin` module may not be using semantic versioning conventions, since the minor bump from `8.8.0` to `8.9.0` depends on a major bump (`2.x.x` to `3.x.x`) for `@google-cloud/firestore`.
