### ISSUE TITLE
After updating to v10.0.0, Cannot find module '@firebase/logger' or its corresponding type declarations. errors occur

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-admin-node#1477]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu
  * Firebase SDK version: "firebase-admin": "10.0.0",
  * Firebase Product: admin
  * Node.js version: 14.18.1
  * NPM version: 6.14.15

### [REQUIRED] Step 3: Describe the problem
After updating to `firebase-admin` v10.0.0, the following Typescript compile errors occurred:
```
node_modules/@firebase/app-types/index.d.ts(17,57): error TS2307: Cannot find module '@firebase/logger' or its corresponding type declarations.
node_modules/@firebase/app-types/private.d.ts(24,37): error TS2307: Cannot find module '@firebase/util' or its corresponding type declarations.
node_modules/@firebase/app-types/private.d.ts(25,45): error TS2307: Cannot find module '@firebase/util' or its corresponding type declarations.
node_modules/@firebase/app-types/private.d.ts(26,53): error TS2307: Cannot find module '@firebase/component' or its corresponding type declarations.
node_modules/@firebase/firestore-types/index.d.ts(18,42): error TS2307: Cannot find module '@firebase/util' or its corresponding type declarations.
node_modules/@firebase/rules-unit-testing/dist/src/public_types/index.d.ts(17,40): error TS2307: Cannot find module '@firebase/util' or its corresponding type declarations.
node_modules/@firebase/storage-types/index.d.ts(25,8): error TS2307: Cannot find module '@firebase/util' or its corresponding type declarations.
```

#### Steps to reproduce:

Update from `firebase-admin` ^9.100.0-alpha.1 -> ^10.0.0.

I noticed, that with this update, the following Firebase packages got deleted from the `package-lock.json` automatically:
* "@firebase/component"
* "@firebase/database"
* "@firebase/logger"
* "@firebase/util"

#### Relevant Code:
N/A
