### ISSUE TITLE
Type error with v9.4.0 and above

### ISSUE THREAD

**Issue by Joshandrews43** [firebase/firebase-admin-node#1186]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OSX 11.1
  * Firebase SDK version: 9.4.0
  * Firebase Product: (auth, database, storage, etc)
  * Node.js version: 14.0.0
   * YARN version: 1.22.10

### [REQUIRED] Step 3: Describe the problem

When I upgraded from 8.4.0 to 9.4.0, I get the following type errors, which seem to not be related to my use of the SDK in any way. It works fine on 9.3.0 and below, but everything above 9.4.0 is broken with zero code changes:

```
node_modules/firebase-admin/lib/firestore/index.d.ts:23:43 - error TS2339: Property 'BulkWriter' does not exist on type 'typeof FirebaseFirestore'.

23     export import BulkWriter = _firestore.BulkWriter;
                                             ~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:23:43 - error TS2694: Namespace 'FirebaseFirestore' has no exported member 'BulkWriter'.

23     export import BulkWriter = _firestore.BulkWriter;
                                             ~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:24:50 - error TS2339: Property 'BulkWriterOptions' does not exist on type 'typeof FirebaseFirestore'.

24     export import BulkWriterOptions = _firestore.BulkWriterOptions;
                                                    ~~~~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:24:50 - error TS2694: Namespace 'FirebaseFirestore' has no exported member 'BulkWriterOptions'.

24     export import BulkWriterOptions = _firestore.BulkWriterOptions;
                                                    ~~~~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:25:48 - error TS2339: Property 'CollectionGroup' does not exist on type 'typeof FirebaseFirestore'.

25     export import CollectionGroup = _firestore.CollectionGroup;
                                                  ~~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:25:48 - error TS2694: Namespace 'FirebaseFirestore' has no exported member 'CollectionGroup'.

25     export import CollectionGroup = _firestore.CollectionGroup;
                                                  ~~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:40:47 - error TS2339: Property 'QueryPartition' does not exist on type 'typeof FirebaseFirestore'.

40     export import QueryPartition = _firestore.QueryPartition;
                                                 ~~~~~~~~~~~~~~

node_modules/firebase-admin/lib/firestore/index.d.ts:40:47 - error TS2694: Namespace 'FirebaseFirestore' has no exported member 'QueryPartition'.

40     export import QueryPartition = _firestore.QueryPartition;
```

#### Steps to reproduce:

Install `firebase-admin@9.4.0` with typescript, then run `tsc`

#### Relevant Code:

```
yarn add @firebase-admin@9.4.0
```

**Comment by hiranya911** [comment]
You need to upgrade the version of `@google-cloud/firestore` installed into your node_modules.
