### ISSUE TITLE
Messaging: TypeError when using providing an app in messaging()

### ISSUE THREAD

**Issue by matteolecuit** [firebase/firebase-admin-node#1598]
### Describe your environment

  * Operating System version: arch linux + kernel v5.16.10
  * Firebase SDK version: v10.0.1 and v10.0.2
  * Firebase Product: messaging
  * Node.js version: v14.17.6
  * NPM version: yarn v1.22.17
  * TypeScript version: v4.5.4

### Describe the problem

We need to specify the app in messaging because we have to run several firebase apps in the same project (as described [here](https://firebase.google.com/docs/admin/setup#initialize-multiple-apps)).

When trying to specify an `App` in `messaging(myApp)`, it thows the exception:
```
error:  TypeError: _this.ensureApp(...).messaging is not a function
    at fn (/home/PROJECT_PATH/node_modules/firebase-admin/lib/app/firebase-namespace.js:131:45)
```
 
#### Steps to reproduce:

Just passing an app that was initialized inside `messaging()` throws.
I can reproduce this error on both `v10.0.1` and `v10.0.2`, but it seems to work on previous versions (at least `v9.12.0` works fine).

#### Relevant Code:

Calling `sendNotification` in the following code would throw an error on `messaging(firebaseApp)` with the error displayed above.
```
import { credential, messaging } from 'firebase-admin'
import { initializeApp } from 'firebase-admin/app'
import { MulticastMessage } from 'firebase-admin/lib/messaging/messaging-api'

const firebaseCredential = credential.cert({
  projectId: '',
  clientEmail: ''
  privateKey: ''
})

const firebaseApp = initializeApp({
  credential: firebaseCredential
})

const sendNotification = async (sendMulticastArgs: MulticastMessage) => {
  return messaging(firebaseApp).sendMulticast(sendMulticastArgs)
}
```

**Comment by lahirumaramba** [comment]
I think you are using a combination of the modular syntax and the deprecated namespaces syntax. Here is an updated code using only the new modular SDK syntax in v10.

```
import { initializeApp } from 'firebase-admin/app'
import { getMessaging, MulticastMessage } from 'firebase-admin/messaging'
import { credential } from 'firebase-admin'

const firebaseCredential = credential.cert({
  projectId: '',
  clientEmail: '',
  privateKey: ''
})

const firebaseApp = initializeApp({
  credential: firebaseCredential
})

const sendNotification = async (sendMulticastArgs: MulticastMessage) => {
  return getMessaging(firebaseApp).sendMulticast(sendMulticastArgs)
}
```

Please see ["Upgrade to Node.js SDK Admin SDK v10 (modular SDK)"](https://firebase.google.com/docs/admin/migrate-node-v10) for more info.
