### PR TITLE
Fix compilation error in integration tests

### PR DESCRIPTION
**Pull request by rsgowman**
Introduced by https://github.com/firebase/firebase-admin-node/pull/790

### CODE REVIEW

**Comment by hiranya911** [comment]
Seems to have been caused by the removal of the following line:

```
// @ts-ignore: purposely unused method.
```

Turns out it's not a TSLint directive, but a compiler directive. 🤦‍♂
