### ISSUE TITLE
Having `@firebase/rules-unit-testing` v3 and `firebase-admin` v11.10.1 in one typescript project creates `database-compat` type errors

### ISSUE THREAD

**Issue by sceee** [firebase/firebase-admin-node#2262]
### [READ] Step 1: Are you in the right place?

I think so.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 11
  * Firebase SDK version: 10.1.0
  * Firebase Product: `firebase-admin` and `@firebase/rules-unit-testing` and `firebase`
  * Node.js version: 18.15.0
  * NPM version: 9.8.1

### [REQUIRED] Step 3: Describe the problem

I have a Firebase functions project that has the following dependencies:
```json
...
"dependencies": {
   ...
  "firebase-admin": "^11.10.1",
  "firebase-functions": "^4.4.1",
  ...
},
"devDependencies": {
  ...
  "@firebase/rules-unit-testing": "^3.0.0",
  "firebase": "^10.1.0", // Peer dependency of @firebase/rules-unit-testing
  ...
}
```

The issue occurred since updating "@firebase/rules-unit-testing" to v3 with "firebase" to v10.

The issue is that after doing this update, the following typescript error occurs:
```typescript
> tsc

node_modules/firebase/node_modules/@firebase/database-types/index.d.ts:176:5 - error TS2717: Subsequent property declarations must have the same type.  Property ''database-compat'' must be of type 'FirebaseDatabase', but here has type 'FirebaseDatabase'.

176     'database-compat': FirebaseDatabase;
        ~~~~~~~~~~~~~~~~~

  node_modules/@firebase/database-types/index.d.ts:169:5
    169     'database-compat': FirebaseDatabase;
            ~~~~~~~~~~~~~~~~~
    ''database-compat'' was also declared here.


Found 1 error in node_modules/firebase/node_modules/@firebase/database-types/index.d.ts:176
```

**I think the error lies somewhere around here:**
In `package-lock.json`, the `firebase-admin` dependency looks like this:
```json
    "node_modules/firebase-admin": {
      "version": "11.10.1",
      "resolved": "https://registry.npmjs.org/firebase-admin/-/firebase-admin-11.10.1.tgz",
      "integrity": "sha512-atv1E6GbuvcvWaD3eHwrjeP5dAVs+EaHEJhu9CThMzPY6In8QYDiUR6tq5SwGl4SdA/GcAU0nhwWc/FSJsAzfQ==",
      "dependencies": {
        "@fastify/busboy": "^1.2.1",
        "@firebase/database-compat": "^0.3.4",
        "@firebase/database-types": "^0.10.4",
        "@types/node": ">=12.12.47",
        "jsonwebtoken": "^9.0.0",
        "jwks-rsa": "^3.0.1",
        "node-forge": "^1.3.1",
        "uuid": "^9.0.0"
      },
      "engines": {
        "node": ">=14"
      },
      "optionalDependencies": {
        "@google-cloud/firestore": "^6.6.0",
        "@google-cloud/storage": "^6.9.5"
      }
    },
```
whereas `firebase` depends on a newer version of `@firebase/database-compat` (1.0.1) that depends on "@firebase/database-types": "1.0.0".

I think that causes multiple versions (0.10.4 as well as 1.0.0) of `@firebase/database-types` to end up in the project causing the TS error.

#### Steps to reproduce:

Have a project that has the dependencies

```json
...
"dependencies": {
  ...
  "firebase-admin": "^11.10.1",
  "firebase-functions": "^4.4.1",
  ...
},
"devDependencies": {
  ...
  "@firebase/rules-unit-testing": "^2.0.7",
  "firebase": "^9.23.0",
  ...
}
```
...that compiles successfully using `tsc`.
Then update `@firebase/rules-unit-testing` to v3 as well as `firebase` to v10. Then `tsc` emits the error mentioned above.

#### Relevant Code:
None.

**Comment by lahirumaramba** [comment]
You are right, `firebase-admin` currently depends on `@firebase/database-compat ^0.3.4`.
`@firebase/database-compat` `v1.0.0` contains breaking changes and the upgrade will be included in the next major version of `firebase-admin`.

In the meantime you will have to use `firebase` `v9`.

**Comment by floinay** [comment]
any updates?
