### ISSUE TITLE
Typescript picking up new errors after upgrading to 9.5.0

### ISSUE THREAD

**Issue by markgoho** [firebase/firebase-admin-node#1185]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 9.4.2 -> 9.5.0
  * Firebase Product: n/a
  * Node.js version: 12.18.3
  * NPM version: 6.14.11

#### Steps to reproduce:

I updated the admin sdk to 9.5.0 and when I try build it will not compile because:
``` bash
node_modules/google-gax/build/protos/iam_service.d.ts:4283:40 - error TS2304: Cannot find name 'Long'.

4283             positiveIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4286:40 - error TS2304: Cannot find name 'Long'.

4286             negativeIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4314:46 - error TS2304: Cannot find name 'Long'.

4314             public positiveIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/iam_service.d.ts:4317:46 - error TS2304: Cannot find name 'Long'.

4317             public negativeIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3761:40 - error TS2304: Cannot find name 'Long'.

3761             positiveIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3764:40 - error TS2304: Cannot find name 'Long'.

3764             negativeIntValue?: (number|Long|null);
                                            ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3792:46 - error TS2304: Cannot find name 'Long'.

3792             public positiveIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:3795:46 - error TS2304: Cannot find name 'Long'.

3795             public negativeIntValue: (number|Long);
                                                  ~~~~

node_modules/google-gax/build/protos/operations.d.ts:4484:31 - error TS2304: Cannot find name 'Long'.

4484             seconds?: (number|Long|null);
                                   ~~~~

node_modules/google-gax/build/protos/operations.d.ts:4500:37 - error TS2304: Cannot find name 'Long'.

4500             public seconds: (number|Long);
                                         ~~~~

[1:37:05 PM] Found 10 errors. Watching for file changes.
```

#### Relevant Code:

I'm not sure why this is happening, but when I revert to the old version the issue goes away.

**Comment by markgoho** [comment]
Sorry fam, this is an [upstream issue in protobuf.js](https://github.com/protobufjs/protobuf.js/issues/1533) but folks are very likely to see this issue when updating their admin sdk package.

**Comment by hiranya911** [comment]
Seems to be a known issue with certain GCP dependencies. There's a workaround documented at https://stackoverflow.com/questions/58159115/error-ts2304-cannot-find-name-long-when-compiling-typescript-with-google-ap

@schmidt-sebastian FYA
